version: 2
accounts:
  - name: user1
    coins: ["1000token", "100000000stake"]
  - name: user2
    coins: ["1000token","5550MYTOKEN"]
  - name: user3
    coins: ["1500token"]  
validator:
  name: user1
  staked: "100000000stake"
